from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from time import sleep
driver = webdriver.Firefox()
# open page to released inmates incarcarated for sex crimes
# driver.get("http://offender.fdle.state.fl.us/offender/offenderSearchNav.do?link=advanced")
names = [
('DOBBINS', 'ELLERY'),
('SMITH', 'JEREMY'),
('BOYD', 'JAMES'),
('SISSON', 'MARK'),
('SMITH', 'JOHN'),
('JENKINS', 'GLENN'),
('KIRLEW', 'SEAN'),
('WHEELER', 'SEAN'),
('MILLER', 'JOHN'),
('CLARK', 'THOMAS'),
('GREEN', 'ROBERT'),
('PAQUET', 'SCOTT'),
('THOMAS', 'DALTON'),
('MILLER', 'HERBERT'),
('JOHNSON', 'DAVID'),
('ADAMS', 'KEVIN'),
('AFRIAT', 'CHARLES'),
('JAMES', 'DARRYL'),
('CAMPBELL', 'JOHN'),
('COHEN', 'ROBERT'),
('MORGAN', 'NICHOLAS'),
('ROSENBERRY', 'RANDY'),
('DYER', 'DAVID'),
('MOORE', 'ANTHONY'),
('JOHNSON', 'DAVID'),
('MIGLIORE', 'ANTHONY'),
('GONZALEZ', 'JOSE'),
('RUSSELL', 'ALYSON'),
('RICHARDS', 'MICHAEL'),
('BROWN', 'CHRISTOPHER'),
('HENSON', 'BRENT'),
('ABRAHAM', 'WILLIAM'),
('NAPIER', 'ALAN'),
('KURTZ', 'CHAD'),
('ALLEN', 'THOMAS'),
('LANE', 'THOMAS'),
('LOPEZ', 'JOSE'),
('JOHNSON', 'CHARLES'),
('SMITH', 'JOHN'),
('MENDEZ', 'ERNESTO'),
('THOMAS', 'BRIAN'),
('TWARDOSKY', 'JOSH'),
('SWAIN', 'LEROY'),
('COBEAN', 'TIMOTHY'),
('RIVERA', 'VICTOR'),
('DAVIS', 'PAUL'),
('MADIEDO', 'CHRISTOPHER'),
('MILLER', 'BRIAN'),
('WILLIAMS', 'JAMES'),
('BROWN', 'JASON'),
('WILLIAMS', 'OTIS'),
('KERSEY', 'RICHARD'),
('BARNES', 'JAMES'),
('HERNANDEZ', 'LUIS'),
('HODGE', 'JAMES'),
('BUSH', 'MICHAEL'),
('JOHNSON', 'CHRISTOPHER'),
('BISHOP', 'DAVID'),
('SMITH', 'STEVEN'),
('CODRINGTON', 'ORES'),
('KRUKOWSKI', 'MICHAEL'),
('BAZARTE', 'RENE'),
('CALVES', 'PATRICIA'),
('FEAGLE', 'LOGAN'),
('SMITH', 'RONALD'),
('CURINGTON', 'RONALD'),
('OLIVER', 'TIMOTHY'),
('MILLER', 'DONALD'),
('LEWIS', 'TROY'),
('DUDLEY', 'SHANE'),
('WRIGHT', 'JACOB'),
('SMITH', 'KENNETH'),
('HOBBS', 'MONTY'),
('CRIST', 'MICHAEL'),
('SCOTT', 'EDWARD'),
('SMITH', 'ROBERT'),
('ALDRIDGE', 'TINA'),
('SMITH', 'ROBERT'),
('KENNEDY', 'DWAYNE'),
('HOWARD', 'MARK'),
('YOUNG', 'JAMES'),
('BAUGUS', 'HUGH'),
('MEHRER', 'JOSEPH'),
('BROWN', 'KENNETH'),
('SERVRANCKX', 'VICTOR'),
('BOUTIETTE', 'JOHN'),
('STARLING', 'JESSICA'),
('VEGA', 'MICHAEL'),
('HALL', 'JESSE'),
('LOVETT', 'ANSEL'),
('YOUNG', 'RONNIE'),
('TOCCO', 'DEVIN'),
('LANGSTON', 'JOE'),
('KEOWN', 'CLAYTON'),
('JEFFORD', 'DAVID'),
('WILSON', 'DONALD'),
('OSBORNE', 'KEVIN'),
('MORGAN', 'CHRISTOPHER'),
('REYNOLDS', 'GWENDOLYN'),
('MEANYHAN', 'JOHN'),
('ROGERS', 'GORDON'),
('BRADLEY', 'CARL'),
('FOWLER', 'RICHARD'),
('BLAKE', 'CALVIN'),
('JOHNSON', 'JEFFREY'),
('MOORE', 'MONTE'),
('HARRIS', 'JASON'),
('JENKINS', 'JOHNNIE'),
('INGRAM', 'CHARLES'),
('ALESSI', 'TIMOTHY'),
('BUTTERS', 'DANIEL'),
('BRANNEN', 'EDWIN'),
('HINTON', 'GARY'),
('WELCH', 'PAUL'),
('GRAY', 'JASON'),
('SINGH', 'SAMUEL'),
('VASSIL', 'DAVID'),
('MCGUIRE', 'PATRICK'),
('SULLIVAN', 'NATHAN'),
('PETERSON', 'ROBERT'),
('STONE', 'DAVID'),
('MAY', 'JOHN'),
('SECURE', 'WILLIAM'),
('SMITH', 'JOSHUA'),
('JOHNSON', 'KEVIN'),
('LOGUE', 'CHRISTOPHER'),
('TAMERIS', 'ROBERT'),
('COLEE', 'ROGER'),
('PRITCHARD', 'FRANK'),
('WEBB', 'ROBERT'),
('VILLIERS', 'RALPH'),
('GRAHAM', 'CHARLES'),
('ROBINSON', 'DERRICK'),
('BRYANT', 'WILLIE'),
('HALE', 'DEWAYNE'),
('BARRETT', 'MATTHEW'),
('BROWN', 'DAVID'),
('SEIGFREID', 'JAMES'),
('MCCRAY', 'DARRIN'),
('LEMANOWICZ', 'CRAIG'),
('DUKES', 'SHEROEN'),
('GRIFFIN', 'KESHARA'),
('DANIELS', 'DERRICK'),
('COX', 'ROBERT'),
('RODRIGUEZ', 'DANIEL'),
('SHEPHARD', 'CHARLES'),
('CORRAO', 'JOSEPH'),
('GARCIA', 'JOSE'),
('JONES', 'JERMAINE'),
('HARRIS', 'KEVIN'),
('WILLIAMS', 'JOHNNY'),
('VANCE', 'WILLIE'),
('MIXON', 'ANTHONY'),
('SPENCE', 'JOHN'),
('HILL', 'ERIC'),
('GONZALEZ', 'JOSE'),
('SMITH', 'MARCUS'),
('JONES', 'COREY'),
('RAMOS', 'CARLOS'),
('COSME-BURGOS', 'VICTOR'),
('PONS', 'ERNESTO'),
('GILBERT', 'JAMES'),
('GONZALEZ', 'JOSE'),
('WILLIAMS', 'JAMES'),
('FLOURNOY', 'MAURICE'),
('RUSSEK', 'JOSEPH'),
('FOSTER', 'CHRISTOPHER'),
('MCDONALD', 'JAMES'),
('DENIRO', 'JOSEPH'),
('RAYL', 'BARRY'),
('WILSON', 'MICHAEL'),
('ROSS', 'EVELYN'),
('SMITH', 'ROBERT'),
('BROWN', 'RICHARD'),
('HEALEY', 'PATRICK'),
('MURPHY', 'JOHN'),
('CRUZ', 'MICHAEL'),
('ANDERSON', 'PHILLINA'),
('JOHNSON', 'MARVELOUS'),
('GEORGE', 'DAVID'),
('HALE', 'TROY'),
('WILLIAMS', 'SHAWN'),
('ROBINSON', 'JENNIFER'),
('RIVERA', 'JOSEPH'),
('VAUGHN', 'TONYA'),
('EBANKS', 'EDWARD'),
('MCDANIEL', 'JOSHUA'),
('LEWIS', 'AMANDA'),
('PAYNE', 'JOSHUA'),
('MUSIELAK', 'THERESA'),
('BLAIR', 'CHRISTOPHER')
]
#text_file = open("A-Matches.txt", "w") 
def checkName(nametuple):
    
    #firstname = driver.find_element_by_name("firstName")
    # open page to released inmates incarcarated for sex crimes
    driver.get("http://offender.fdle.state.fl.us/offender/offenderSearchNav.do?link=advanced")
    sleep(4)
    lastname, firstname = nametuple
    driver.find_element_by_name("firstName").send_keys(firstname)
    driver.find_element_by_name("lastName").send_keys(lastname)
    driver.find_element_by_xpath("/html/body/div/div/div/div/div/form/table/tbody/tr[7]/td[2]/a").click()
    sleep(3)
    #present = driver.find_element_by_class_name("ResultsPhoto")
    try:
        notpresent = driver.find_element_by_class_name("error-text")
        if notpresent:
            print(" Not Present ")
    except:
        print(firstname + " " + lastname)
        print(" Present ")
    html = driver.page_source
    # print(html)
    
for name in names:
    checkName(name)
    
#text_file.close()